### ISSUE TITLE
Exception thrown when showing redaction plan

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/ImageDePHI#240]
I get an exception
```
Traceback (most recent call last):
  File "imagedephi/__main__.py", line 4, in <module>
    main.imagedephi()
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "imagedephi/utils/cli.py", line 48, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 38, in new_func
  File "imagedephi/main.py", line 161, in plan
    show_redaction_plan(input_path, obj.override_rule_set, recursive, strict)
  File "imagedephi/redact/redact.py", line 256, in show_redaction_plan
    redaction_plan_report.update(redaction_plan.report_plan())  # type: ignore
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "imagedephi/redact/svs.py", line 214, in report_plan
    rule = self.metadata_redaction_steps[tag.value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 55000
```
when trying to show the redaction plan for an svs file that includes a tiff tag 55000;
```
  AperioUnknown55000 55000 (0xD6D8) SLONG: <4> 26189 16457 48906 52762
```

**Comment by naglepuff** [comment]
Fixed by https://github.com/DigitalSlideArchive/ImageDePHI/commit/ef6d1a3735e633514efdb9b2ab126ea8e0bde730
